// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// BELOW WAS SUJIT'S PERSONAL CREDENTIALS
// const SUPABASE_URL = "https://bqqsbogrswpmicfaicme.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxcXNib2dyc3dwbWljZmFpY21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTM2ODIsImV4cCI6MjA2MzkyOTY4Mn0.TPd-21zbF7y2lu3rsgjweajzuXIcGREVdeBhfNhSvbw";


// ADDING COMPANY SUPABSE CREDENTIALS IN COMMENT JUST IN CASE (SAME IN ENV FILE)
// VITE_SUPABASE_URL=https://kbkmwswlkwkhabzugbpi.supabase.co
// VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtia213c3dsa3draGFienVnYnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTUyNDAsImV4cCI6MjA2NjY3MTI0MH0.ZOb4_GJh5Jzr7S4m7-5Nmjmb236za2qZBCUsxfhSyBA


const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);
